### ISSUE TITLE
Remoting: customHandler is not configured.

### ISSUE THREAD

**Issue by orifjonmelibayev** [SitecorePowerShell/Console#1097]
`Invoke-RemoteScript` uses script endpoint `$serviceUrl = "/-/script/script/?"` (line 299)
But this endpoint is not configured in customHandlers.

### Expected Behavior
Scripts should run

### Actual Behavior
404 error returned from sitecore.

### Steps to Reproduce the Problem

run `Invoke-RemoteScript` with `-Verbose` option to see error message.  

SPE version: 5.0
Sitecore version:9.1

 - [X] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
I did not think of a more creative name. If it should be renamed I'm happy to accept suggestions.

This feature is an in place replacement for the existing remoting endpoint. If you already have remoting enabled then this should just work. The handler is the existing one that handles file and media uploads.

**Comment by orifjonmelibayev** [comment]
I've upgraded SPE from 4.7.2 to 5.0 and my remote calls stopped working. Quick analyzing the issue showed that, service url changed to `/-/script/script`. probably we should add something like `<handler trigger="-/script/script/" handler="RemoteScriptCall.ashx" />` to config file and make sure endpoint can handle this.

**Comment by michaellwest** [comment]
SPE 5.0 Remoting did not make use of that path. The current master (5.1) adds support for this in both the RemoteScript handler and the SPE Remoting powershell module. 

Were you using a mismatch of versions?

**Comment by orifjonmelibayev** [comment]
I downloaded SPE 5.0 (latest) full version from marketplace and remoting
module from PSGallery. It contains version 5.0 only.

Having version 4.7.2 remoting module in PSGallery also helps.

Kind regards,
Orifjon

**Comment by michaellwest** [comment]
@orifjonmelibayev It all is clear to me now what happened. When I published the module 5.0 on PowerShell Gallery, the package had the incorrect version of `Invoke-RemoteScript`. That was completely my fault. I've unlisted the module version 5.0 and published two other versions.

* Version 4.7 represents the version of SPE Remoting on the Marketplace with the description updated.
* Version 5.0.1 represents the version of SPE Remoting on the Marketplace with the description updated and version changed from 5.0 to 5.0.1. This is only due to the fact that I can't unpublish the module 5.0.0.

With that said, the handler code should not be necessary since it was all a mistake on my part regarding the version on the Gallery. Moving forward I will use the 3 digit version number.
