### ISSUE TITLE
Interactive message results in an error matching parameter `var0string`

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1122]
Running the following script in the ISE, followed by inputting a value results in an error.

```powershell
function Say-HelloToIza {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]$Message
    )
    
    Write-Host $Message
}

Say-HelloToIza
```

![image](https://user-images.githubusercontent.com/933163/61225518-57f6ed00-a6e6-11e9-9eea-b573ec99a98d.png)

![image](https://user-images.githubusercontent.com/933163/61225536-63e2af00-a6e6-11e9-9aef-a01ebb216909.png)

Thank you @izabelawlodarska for reporting the issue.

**Comment by michaellwest** [comment]
This appears to be related to `PowerShellMultiValuePrompt.cs` where the variable is received by not properly returned with the right now.

**Comment by AlexKasaku** [comment]
This was traced back to a long-standing bug in the `ScriptingHostUserInterface.cs` code that would automatically assign generated names to parameters, but would not use names provided to the prompt if there are any.

Another way to see this bug is to simply run a command that has mandatory parameters but not include them, such as `Get-Item`, which will prompt for a Path:

![image](https://user-images.githubusercontent.com/1439631/61396741-4d904b00-a8c0-11e9-8140-74b80c506185.png)

This would also present the same bug. The fix added covers both this scenario and the presented in the issue itself.
