### ISSUE TITLE
Index commands like Remove-SearchIndexItem do not use the Name parameter

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#1146]
Noticed while trying to remove items from the index that the index database name is pulled from the property `item.Database.Name` and not from the optional `-Name` parameter.

Right now if you need to remove the item from _sitecore_web_index_ you have to first query the item from the web database.

https://github.com/SitecorePowerShell/Console/blob/0d7999d757158a0461ead0edf640e219fbe27378/Spe/Commands/Data/Search/RemoveSearchIndexItemCommand.cs#L30

**Example:** The following does not work when trying to remove the item from the web index.
```powershell
$item = Get-Item -Path "master:" -ID "{GUID_HERE}"
Remove-SearchIndexItem -Item $item -Name "sitecore_web_index"
```

**Comment by AlexKasaku** [comment]
This looks like this is due to this check which confirms there is a Crawler on the right database before attempting to remove the item:

`if (!index.Crawlers.Any(c => c is SitecoreItemCrawler crawler && crawler.Database.Is(itemDatabase))) continue;`

Does that check need to exist?

**Comment by AlexKasaku** [comment]
The Remote-SearchIndexItem no longer considers the database of the item that is being removed, as it just uses the ID for removing the item.

Adding an item to the index does still consider the database - since the crawler performs this check at a later point anyway, there is little point in skipping the check in that instance.
