### ISSUE TITLE
Remoting: Get-Item -Path not found

### ISSUE THREAD

**Issue by bohessner** [SitecorePowerShell/Console#1181]
### Expected Behavior

Get-Item should return item

### Actual Behavior

Get-Item will not return any new items

### Steps to Reproduce the Problem

SPE version 5.1. 
Sitecore.NET 8.1 (rev. 151207)

I duplicate the item: **tabs** and name the copy: **xxx** inside the sitecore backend. Then I make the Get-Item calls.

![image](https://user-images.githubusercontent.com/30377362/77925634-62253f80-72a5-11ea-8702-5233274fbfa8.png)

Everything are normal.

Then I try **Get-Item** from **remote**:

![image](https://user-images.githubusercontent.com/30377362/77925752-8aad3980-72a5-11ea-8bdd-b99a143d21ec.png)

Any ideas? (have also tried with -ID)

**Comment by michaellwest** [comment]
Your two calls to get item are different. You should not have Sitecore in the path.

**Comment by bohessner** [comment]
Same result:

![image](https://user-images.githubusercontent.com/30377362/77927218-563a7d00-72a7-11ea-994d-6b6d67948d3c.png)

**Comment by bohessner** [comment]
The output from inside the Sitecore backend are different from the remote response. I see a "Version Id", this is not showing up when calling remote. The "Languages" are also different.

**Comment by michaellwest** [comment]
I would not be concerned about the format. This is due to the fact that there is a format file included with SPE and it may be different than what is included in the remoting module. It is up to the developer to specify how they wish to format the response data if they want to show it in the host console. 

At the end of the day this doesn't really matter because you can use Select-Object to return less data from the server and Format-Table to properly format in the PowerShell window. Be mindful that the data coming back is serialized and then deserialized so you can't use it expecting everything to behave the same like in the SPE ISE.

In essence I believe everything is working as expected.

**Comment by bohessner** [comment]
I hear you. 

But, as you can see, the first remote call return ok(**Tabs**) and _the the call just after_ do not(**xxx**).  For some reason I can not figure out, for now.

**Comment by michaellwest** [comment]
What happens if you make just one call for the xxx item?

**Comment by bohessner** [comment]
Same thing (but it will return just fine from inside SPE ISE)

![image](https://user-images.githubusercontent.com/30377362/77938959-c56b9d80-72b6-11ea-95fc-de6b9bb1df40.png)

**Comment by michaellwest** [comment]
Perhaps a silly question but are connecting to the same instance?

**Comment by bohessner** [comment]
Thx, thx, thx - my instance names are so similar. I was blind, but now I see :-)
