### ISSUE TITLE
Out-Download should error if fileDownload not enabled

### ISSUE THREAD

**Issue by dsolovay** [SitecorePowerShell/Console#1206]
### Expected Behavior

If configuration element /sitcore/powershell/services/fileDownload[@enabled]= false, the Out-Download should return an error indicating that this configuration element must be changed for the command to work.

### Actual Behavior

The command returns True, but does not generate a download.  A 401 error is visible in the browser console.

### Steps to Reproduce the Problem

_Please include the version number of SPE and Sitecore._ Sitecore 9.2, SPE 5.1

 - [ ] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [x] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

**Comment by michaellwest** [comment]
I tested this with 6.1.1 and this is the current behavior when the "handleDownload" service is disabled.

![image](https://user-images.githubusercontent.com/933163/90341515-cda64a00-dfc5-11ea-8601-cf6733f8ef7c.png)

Looks like up to this point the feature is enabled by default because you are already logged into the Sitecore client. Good news is no change is needed.

@dsolovay Did you have a custom config which disabled this as part of your solution? Can you share what that patch looked like?
