### ISSUE TITLE
How to uninstall\remove Poweshell extensions from Sitecore?

### ISSUE THREAD

**Issue by HanuChannamsetti** [SitecorePowerShell/Console#1224]
There is security concerns with having the Powershell extensions on our Sitecore instance. I am trying to remove the module and would really appreciate any help on how to do it.
Thanks

**Comment by michaellwest** [comment]
Can you provide a list of the security concerns?

**Comment by HanuChannamsetti** [comment]
Hi Michael, 

We are in process of moving our Sitecore to AWS and based on the company security policies it is not allowed to have the ability to restart app pool or any such access level for Sitecore users. It is either remove the PowerShell extension from our Sitecore or remove admin rights to the Sitecore.  So we are trying to remove the PS.

**Comment by bRaInT00T** [comment]
I believe these concerns are around having remote PowerShell access to a server.  Are there limitations to the commands available to be executed from the console?  I've noticed that the runas account is not configured as an administrator account, but if this is a full blown PowerShell console, malicious or not, it has the ability to be pretty dangerous on a production server.

**Comment by michaellwest** [comment]
The module does not have more access than what you give to it. If the service account running the website has access to change system settings then you're already off to a bad start.

Since SPE is only installed for the standalone or content management role the risk is limited to those servers. Ensure the service account has low privileges and you drastically reduce the problems it can cause. 

It's no more risky then writing malicious c# code. If someone can deploy their own DLL they could certainly do worse, and have unit tests to validate!

You are way better off having the module installed, leveraging the capabilities, then stressing out about the kind of problems a junior dev could do in other ways.

Read more about it in the book.

**Comment by HanuChannamsetti** [comment]
Thank you for the information Michael. Will definitely try to follow the security guidelines. 
Right now we are very close to this migration to AWS and looking for every option to mitigate this issue. 

To remove the Sitecore powershell module. The only way I can think of doing it is to unpublish the /sitecore/system/Modules/PowerShell.
Please suggest the right steps.

**Comment by HanuChannamsetti** [comment]
@michaellwest  Please advice on how to remove the PS from Sitecore.
Really appreciate any help.

**Comment by michaellwest** [comment]
Removing follows the same process you would for any other module. 

You delete the configs, dlls, and any other files output by the package. Then you delete all of the items that were added by the package.

**Comment by HanuChannamsetti** [comment]
Great! thank you
