### ISSUE TITLE
Receive-file dialog errors out when invalid file name upload is attempted

### ISSUE THREAD

**Issue by WDrake98** [SitecorePowerShell/Console#1241]
### Expected Behavior

When I attempt to upload a file with an invalid character in the file name, I should get a warning that file is invalid

### Actual Behavior

An alert dialog appears that's too small to read and file is not uploaded. 

### Steps to Reproduce the Problem

Sitecore.PowerShell.Extensions-6.1.1
Sitecore 9.2 base install 

1. run script Receive-File -ParentItem (get-item "master:\media library\Files") 
2. select a file with parentheses in the file name. I.e., apples(1).txt
3. select upload
4. Error box will appear that's unreadable
5. Errors in logs show error message  

 - [x] Tested issue with clean install of Sitecore and the latest available version of SPE.
 
 - [ ] Asked questions on the Sitecore Slack Chat channel.
 
 - [ ] Reviewed questions and answers on the Sitecore Stack Exchange.

![image](https://user-images.githubusercontent.com/5875789/121215634-cea2b380-c845-11eb-8cf5-b17b230a31a2.png)

Error Message:
17172 10:13:22 ERROR One or more exceptions occurred while processing the subscribers to the 'item:creating' event.
Exception[1]: System.ArgumentException 
Message[1]: 'Name' should consist only of letters, digits, dashes or underscore 
Source[1]: Sitecore.Marketing.Core 
   at Sitecore.Marketing.Core.Extensions.ConditionValidatorExtensions.IsValidAlias(ConditionValidator`1 validator)
   at Sitecore.Marketing.xMgmt.Definitions.ItemEventHandler.ValidateItemName(ItemData itemData)
   at Sitecore.Marketing.xMgmt.Definitions.ItemEventHandler.OnItemCreating(Object sender, EventArgs args)
   at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result) 

17172 10:13:22 ERROR Could not save posted file: HedgehogError(1).txt
Exception: System.AggregateException
Message: One or more exceptions occurred while processing the subscribers to the 'item:creating' event.
Source: Sitecore.Kernel
...

Nested Exception

Exception: System.ArgumentException
Message: 'Name' should consist only of letters, digits, dashes or underscore
Source: Sitecore.Marketing.Core
   at Sitecore.Marketing.Core.Extensions.ConditionValidatorExtensions.IsValidAlias(ConditionValidator`1 validator)
   at Sitecore.Marketing.xMgmt.Definitions.ItemEventHandler.ValidateItemName(ItemData itemData)
   at Sitecore.Marketing.xMgmt.Definitions.ItemEventHandler.OnItemCreating(Object sender, EventArgs args)
   at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result)

**Comment by michaellwest** [comment]
Tested with 10.2 XM and didn't see the error. Curious why it happens for XP.

![image](https://user-images.githubusercontent.com/933163/157805009-c4376650-0c95-4493-a51e-e33f402bf95b.png)

**Comment by AdamNaj** [comment]
A few things:
- it looks like the upload might be sanitized now, Michael is right to say that uploading such files does not seem to be causing much problem. 
- there was a general problem with the dialog not working at all due to Sitecore security measures taken in 10.3, where every method that can be called from the front end must be registered as allowed.
- There was a general problem with that dialog showing any kind of Exception due to some JS or HTML changes in Sitecore. I've changed how the errors are shown. Starting from now you will not see an allert window but rather a message bar on top of the dialog instead showing the exception message.

![image](https://github.com/SitecorePowerShell/Console/assets/1209953/b3caef62-264e-4c98-84f0-7bb7dba8022c)
