### ISSUE TITLE
Page Editor integration point - script button

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#1276]
### Steps

- install **[20220818.0825.Test-1.zip](https://github.com/SitecorePowerShell/Console/files/9368357/20220818.0825.Test-1.zip)** package - PE integration point
- open browser using guest/incognito 
- navigate directly to home item - without CE
- click button

### Expected Behavior / Actual Behavior

I can run interactive scripts in EE/PE. Right now it cannot show **List View**. See video.

https://user-images.githubusercontent.com/6848691/185325775-7359ae7f-b163-470a-82e1-712363089e3e.mp4

### Additional info

I noticed that issue is gone when you open item using CE (included in the video).

Here is a difference between two requests (initial, after item was opened in CE)
![image](https://user-images.githubusercontent.com/6848691/185331660-8c805c2a-c10d-488b-9911-4a529be3654a.png)

Raw files:
- [bug.txt - left](https://github.com/SitecorePowerShell/Console/files/9368442/bug.txt)
- [oke.txt - right](https://github.com/SitecorePowerShell/Console/files/9368443/oke.txt)

**Comment by AdamNaj** [comment]
Fixing this may require some serious digging, but we can avoid it... 
I accidentally found this out when trying other scripts with this method... this will work if `Show-Listview` is executed with `-Modal` parameter. 
I suspect that's because Experience Editor is a full-screen app and misses some window handling.
