### ISSUE TITLE
Supressing the "Running script" dialog, when calling script from the Content Editor

### ISSUE THREAD

**Issue by KurtBildeSDU** [SitecorePowerShell/Console#1342]
This is a wish, not a bug :-)

We use spe for specilized functionality directly from the content editor via the right click menu (like "move and create redirect to new item"). When running a script from the content editor, the editors sometimes gets worried when seeing the "running script" dialog. It could be nice if the dialog could be disabled via a parameter in the code.

![Running_script_dlg](https://github.com/SitecorePowerShell/Console/assets/49776085/1d206928-e81f-4b62-84e5-543f17542f02)

**Comment by AdamNaj** [comment]
The problem is that the dialog is the vehicle for surfacing all of the US events as it hosts the job-polling JS monitor.
Concerning the message that is displayed - I wonder if you are aware of the ability to change the message:

https://www.youtube.com/watch?v=lygOuOApmRc

``` PowerShell
# Show message with Write-Progress cmdlet
Write-Progress -Activity "This is Activity" -Status "This is status" -CurrentOperation "This is Current Operation"

# Pause for 50 milliseconds
Start-Sleep -Milliseconds 5000

#Close the window after script finishes
Close-Window
```

While implementing a new approach would not be impossible I think the provided solution solves the business problem of removing the anxiety for your editors and even potentially informing them about the progress `Write-Progress` with and then dismissing the dialog automatically with `Close-Window`

Should you feel like this does not solve the issue, feel free to re-open the

**Comment by KurtBildeSDU** [comment]
Hi Adam
I am aware of the posibility to change the dialog (see attached dialog). At the end of the day it is not a turning point for not using SPE - it is more nice than need :-)

Thanks for you attention!!!
