### ISSUE TITLE
Build in a "Smart Copy"-function

### ISSUE THREAD

**Issue by KurtBildeSDU** [SitecorePowerShell/Console#1343]
This is not a bug but a wish.

We have code, examples, but it would be "smart" with a build in "smart copy"-function in spe, that takes care of both the item and the datasources of the renderings. See this example by Steve Vandenbush:

https://vandsh.dev/sitecore/2019/01/09/spe-single-item-smart-copy.html. 
The spe function should of course be without the dialogs :-)

**Comment by AdamNaj** [comment]
It sounds cool! 

It also sounds like a bit much responsibility to add to `Copy-Item` that feels a little bit situational and potential support challenge in the making due to all the complex scenarios it can get into (what about references of the references 😄? What about SXA-like local references that may not exist in the Link database 😃?)

@KurtBildeSDU I'm sure we'd love to consider it if you decided to contribute and maintain it, but seeing how a solution already exists in the community I'd pass on developing one myself.

@michaellwest - you up for the challenge?
