### ISSUE TITLE
Powershell script is given error 

### ISSUE THREAD

**Issue by iprateeksunny** [SitecorePowerShell/Console#1344]
Expected Behavior
When we run Powershell script in Powershell ISE in Sitecore. Then it should generate the desired output/result. We are expecting 10000 items as output from the script.

Actual Behavior
In Sitecore 10.2 environment, when we are running Powershell script on PowerShell console. After some time, we are seeing one exception and script execution is failing.

Steps to Reproduce the Problem
We copy the script and open Powershell ISE and execute the script then after some time we see below error:

Find-Item : Exception of type 'System.OutOfMemoryException' was thrown.
At line:69 char:18
+ ... exedItems = Find-Item -Index sitecore_master_index -ScopeQuery $scope ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Find-Item], OutOfMemoryException
    + FullyQualifiedErrorId : System.OutOfMemoryException,Spe.Commands.Data.Search.FindItemCommand

And it is happening with every script.
Sitecore Version: 10.2
Powershell Version: 6.3
I have attached the script. 
[PS_Script.txt](https://github.com/user-attachments/files/16099885/PS_Script.txt)

**Comment by michaellwest** [comment]
You may be able to avoid this issue by using paging with Find-Item. You're bringing back potentially more data than you have memory.

**Comment by iprateeksunny** [comment]
Thanks Michaell. Is there any example that I can follow to implement paging with Find-Item?

**Comment by AdamNaj** [comment]
I'm not seeing an error that SPE would be at fault. The problem happens internally as Sitecore process gets overwhelmed by the unmber of items . 10k items is simply excessive to load to memory at a time especially since You are later materializing them as full Sitecore items with Initialize-Item.

Using `-First`, `-Skip` and `-Last` parameter should be used to create some sort of paging or limiting the number of items loaded at once to the minimum.
