### ISSUE TITLE
New Pipeline invoking commands

### ISSUE THREAD

**Issue by scjunkie** [SitecorePowerShell/Console#216]
Invoke-Pipeline ==> this would wrap Sitecore.Pipelines.CorePipeline.Run() methods
Invoke-ClientPipeline ==> this would wrap Sitecore.Web.UI.Sheer.ClientPage.Start()

**Comment by AdamNaj** [comment]
Just looked into implementing this and I'd very much like your opinion on it @scjunkie:
* For the CorePipelines: 
  * Since virtually every pipeline is running with its own parameters the plumbing that we remove by adding our own cmdlet is minuscule as the class needs to be created by the user anyway.
* for ClientPage pipelines:
  * Virtually all of those I can think of are reachable by running `Invoke-ShellCommand` with a relevant command and item, which I find somewhat easier to use and understand.

Feel free to re-open it if you feel that I was misguided or find a good scenario where this would be worthwhile using.

**Comment by AdamNaj** [comment]
Talked to mike offline and we agreed that the benefits of this functionality from the "code saving" perspective would be marginal. Closing it off as "won't fix" as discussed.
