### ISSUE TITLE
Rename commandlets to adhere to list of PowerShell approved Verbs

### ISSUE THREAD

**Issue by AdamNaj** [SitecorePowerShell/Console#270]
Rename the following commandlets & add aliases to their old names:

Should be | Was |
--------- | --- |
Export-Item | Serialize-Item
Import-Item | Deserialize-Item
Invoke-Script | Execute-Script
Invoke-ShellCommand | Execute-ShellCommand
Invoke-Workflow | Execute-Workflow
Install-Package | Import-Package
Initialize-Item | Wrap-Item
Send-File | Download-File

**Comment by michaellwest** [comment]
Yes!

**Comment by AdamNaj** [comment]
Implemented :)

**Comment by michaellwest** [comment]
Shouldn't it be the following relationship for downloading and uploading?

| Should Be | Was |
| - | - |
| Send-File | Upload-File |
| Receive-File | Download-File |

Since it's from the perspective of the user, you send a file up to the server, and receive a file down from the server. Right? If you agree I'll commit my changes.

**Comment by AdamNaj** [comment]
I was thinking about it both ways. I think it's usually from the server's perspective. It's server that does the Sending and Receiving.

If you read the (Approved Verbs Page)[tps://msdn.microsoft.com/en-us/library/ms714428%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396] it says:

```Send``` - Delivers information to a destination. (I consider user the destination)
```Receive``` - Accepts information sent from a source. (user being the source)

Besides I don't think we can just swap them now as it will break people's scripts if they used the commandlets we have now.
