### ISSUE TITLE
Rules based report encounters maxClauseCount issue on Sitecore 7.0 (rev. 140408)

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#384]
```powershell
Find-Item : maxClauseCount is set to 1024
At line:40 char:19
+ $templateFields = Find-Item -Index sitecore_master_index -Criteria @{Filter = "S ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Find-Item], TooManyClauses
    + FullyQualifiedErrorId : Lucene.Net.Search.BooleanQuery+TooManyClauses,Cognifide.PowerShell.Commandlets.Data.FindItemCommand
```

**Comment by AdamNaj** [comment]
This took some serious digging - it's not a limitation of Sitecore version per-se but rather a function of the instance and the number of items processed - and rubs against how Lucene works and how the search phrases are built. Basically we're learning it now because I have never tested it against a root with more than 1024 descendants. If you will run the report against the root of content tree in Sitecore 8 it will bomb as well.

In the next version of SPE you will be able to do just the following:
```powershell
Find-Item -Index sitecore_master_index -Criteria @{Filter = "DescendantOf"; Value = $root}
```
And that's how I've solved this problem in the long run in our script - by extending the Find-Item. But for now you can replace this bit of code:

```powershell
$templateFields = Find-Item -Index sitecore_master_index -Criteria @{Filter = "StartsWith"; Field = "_fullpath"; Value = "$($root.Paths.Path)"} | 
```

with this:
```powershell
$rootId = $root.ID.ToShortID().ToString();
$templateFields = Find-Item -Index sitecore_master_index -Criteria @{Filter = "Contains"; Field = "_path"; Value = "$rootId"; CaseSensitive=$false} | 
```

And that should solve the problem.

**Comment by AdamNaj** [comment]
Implemented
