### ISSUE TITLE
Write Streams should output to ISE results pane in real time

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#436]
Write-Progress is great but doesn't always give enough detail for someone to decide if an Abort is needed. Can we have the other Write streams output to the blue pane incrementally rather than at the very end?

**Comment by pveller** [comment]
Like! Maybe just have another area that the output stream attaches to? Imagine your `please wait` message and then another *window* with the console log. I would imagine right now you are *collecting* the output into a buffer that you display upon completion of the script execution. The interface doesn't freeze or anything so the issue is really where the output stream attaches to. Right?

**Comment by michaellwest** [comment]
From what I can see, the write-progress command puts messages in a queue that is picked up by the ISE. I imagine there is not much effort required by our Senior SPE engineer Adam. I bet he could even add it to 3.3 because that release is focused on gold plating SPE. ;-)

**Comment by AdamNaj** [comment]
I'll handle that :)

**Comment by michaellwest** [comment]
It better work right. ;-)

**Comment by AdamNaj** [comment]
Implemented.
