### ISSUE TITLE
Can/Should Get-Item respect -EA SilentlyContinue ?

### ISSUE THREAD

**Issue by pveller** [SitecorePowerShell/Console#500]
It would be nice if the following returned one result:

```
"oops|/sitecore".Split('|') | Get-Item -ErrorAction SilentlyContinue
```

Instead it fails with:

```
Get-Item : Path '{0}' does not exist
Parameter name: master:\a
At line:1 char:1
+ Get-Item -Path "a" -ea SilentlyContinue
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Item], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.GetItemCommand
```

**Comment by michaellwest** [comment]
Hey @pveller, looks like the version under development has this issue corrected. I ran your script and both the formatted text in the event the error is shown.

**Comment by AdamNaj** [comment]
It does not appear to fail for me either. 
If I execute the command using your one-liner and am in context of a master:\ location I simply get the /sitecore item.

```powershell
PS master:\>"oops|/sitecore".Split('|') | Get-Item -ea SilentlyContinue
 
Name                             Children Languages                Id                                     TemplateName
----                             -------- ---------                --                                     ------------
sitecore                         True     {en}                     {11111111-1111-1111-1111-111111111111} Root
```
Are you on the 3.3 version? I believe I was touching some of this 3.0, but for sure it should be working as that is how @Kasaku implemented #480. Although as [this generic PowerShell SO answer seems to suggest - not always super reliably](http://stackoverflow.com/questions/17489372/ls-recurse-erroraction-silentlycontinue-doesnt-work).

Since the functionality of handling of EA in this scenario is in PowerShell's responsibility I would examin the version of PowerShell installed on the server and potentially upgrade it to 4.0 if it's not already there and is possible.

One thing that makes me wonder though is the text of the error message. The ```{0}``` should never be there and instead should show the path provided as the parameter, it seems as your error is not consistent with the command you have provided.

**Comment by pveller** [comment]
This is from PSE 3.0 on 2008 R2 under SC 8 Update 3 with Powershell 4

**Comment by pveller** [comment]
>> your error is not consistent with the command you have provided.

definitely coming from that one liner. I copy-pasted directly from my screen.

**Comment by michaellwest** [comment]
So using SPE 3.0 instead of 3.3?

**Comment by pveller** [comment]
Using 3.0 on that machine, yes. Not really *instead* :) just didn't upgrade to 3.3 yet

**Comment by AdamNaj** [comment]
3.0 is really behind. I'd suggest upgrading :) It should be pretty seamless.

**Comment by AdamNaj** [comment]
Hi Pavel, 
when you have a chance to do it, feel free to close or elaborate on the issue.

**Comment by AdamNaj** [comment]
Closing as it appears it was fixed in previous versions.
