### ISSUE TITLE
Sitecore package installation is failed with PowerShell

### ISSUE THREAD

**Issue by narayana100** [SitecorePowerShell/Console#533]
Hi,
I am getting the below error while installing the packages in Sitecore through Powershell.

![sitecore_error](https://cloud.githubusercontent.com/assets/16244921/11724493/612f3f8c-9f9a-11e5-93b7-185e11fb60d7.PNG)

Please help me to resolve the issue.

Thanks,
Narayana

**Comment by AdamNaj** [comment]
From the error I can see that you're using remoting to do the job install the package over on an external Windows Powershell environment and a call times out.

The error you see is showing up because the package installation process takes longer than the time it takes the remoting web service to time-out. The package in fact probably succeeds to install but the call never lasts so long to see it work.

What you need to do is to spin up a background session in your remote call rather than installing the package in the main thread. You can find [quick crash-course in background session handling in this video](https://www.youtube.com/watch?v=zNyVrj1vH6c) and a sample in how to wrap a bit of functionality in backround session in the `10_Execute-LongRunningRemoteFunctionAndWaitForResults.ps1` gist [here](https://gist.github.com/AdamNaj/1b46da24ed8ed6b84593#file-10_execute-longrunningremotefunctionandwaitforresults-ps1)

**Comment by narayana100** [comment]
Hi AdamNaj,

We are unable to run import-module SPE looks like we don't have module SPE. 
we are getting following error.

![error](https://cloud.githubusercontent.com/assets/16244921/12088616/e254302e-b302-11e5-8753-b87b3a467d53.JPG)


![image](https://cloud.githubusercontent.com/assets/16244921/12088590/bfc8c36c-b302-11e5-8002-f9bda5fc354c.png)

**Comment by michaellwest** [comment]
You should be able to find the module out on github here:
https://github.com/SitecorePowerShell/Console/tree/master/Data/packages

SPE Remoting 3.3

**Comment by narayana100** [comment]
Hi Michaellwest,
I have taken the SPE module and tried it but I am getting the following error.

![sc](https://cloud.githubusercontent.com/assets/16244921/12094498/f5829056-b32e-11e5-8658-d4f0367a8b83.JPG)

**Comment by AdamNaj** [comment]
If you can hang on just a little bit longer, I know @michaellwest have implemented a great functionality for long running scripts over remoting for SPE 4.0. We will be coming with some tutorials in the book as well as some videos on our YouTube channel.

**Comment by narayana100** [comment]
Thanks for your information.
When can we expect the SPE 4.0? Please share the link if available.

**Comment by AdamNaj** [comment]
I would expect the next version to be generally available within the next 1-2 weeks.

**Comment by narayana100** [comment]
Okay. Thanks for your support. Please let me know once its released.

**Comment by AdamNaj** [comment]
Closing as 4.0 was released in the mean time.
