### ISSUE TITLE
Sitecore 7.2, Open menu expand throws error

### ISSUE THREAD

**Issue by crsnt** [SitecorePowerShell/Console#582]
SPE 3.3 - In Powershell ISE, clicking little arrow of the 'Open' command throws this error:

startIndex cannot be larger than length of string.
Parameter name: startIndex

![spe error](https://cloud.githubusercontent.com/assets/1879280/13037329/6daa5db6-d3b9-11e5-805d-f52b98470e64.png)

**Comment by AlexKasaku** [comment]
I'm able to reproduce this (though I don't get the popup, the error happens in the background and is reported in the console), though not in a position to apply a fix today. But I can provide information:

This happens when a script is saved into the top-level Script Library folder, e.g. `/sitecore/system/Modules/PowerShell/Script Library`

I suspect it is down to this line:

```c#
control["Location"] = scriptItem.Paths.ParentPath.Substring(ApplicationSettings.ScriptLibraryPath.Length);
```

Which will effectively call Substring with the length of the whole path, which as its zero-indexed is one digit over.

**Comment by AdamNaj** [comment]
That's exactly it! Fixed now :)

**Comment by AdamNaj** [comment]
Attributing the fix to @AlexKasaku as he's the one who provided the fix that I merely committed.
