### ISSUE TITLE
Read-Variable dialog should support placeholder text for multiline textboxes

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#700]
Having to delete the text first doesn't make for a good user experience.

**Adam's edit:**
Modified this issue to say that can still be added to multiline text box

**Comment by AlexKasaku** [comment]
Freebie feature alert - It looks like it already does! I started digging through the code and could see that the modal dialog does already have support for a Placeholder property on the Parameter. I took a shot at adding it to Read-Variable to see if it would be picked up and it os:

```
$result = Read-Variable -Parameters @{ Name = "someText"; Placeholder="Some Text"; Title="Single Line Text"; Tooltip="Tooltip for singleline"}
```

However, the property isn't mentioned in the Read-Variable documentation so that needs updating.

**Comment by michaellwest** [comment]
Oh yeah, I added that!

**Comment by AdamNaj** [comment]
Added support for multiline textboxes.
Added samples to documentation and sample script.
