### ISSUE TITLE
Update ribbon on paste in standalone PowerShellIse

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#794]
**Actual result:**
Once I paste long script in standalone **ise** (`http://domain/sitecore/shell/Applications/PowerShell/PowerShellIse?sc_bw=1`) I have to wait 2 seconds until `updateRibbon` function will be called to get proper look and feel.

![how to reproduce](https://cloud.githubusercontent.com/assets/6848691/22003259/61dadd24-dc52-11e6-900b-111129ba15a0.gif)

**Expected result:**
Ribbon should be updated instantly.

**Comment by AdamNaj** [comment]
This behaviour is intentional to avoid flooding server with excessive number of calls to rebuild the ribbon. The call is made 2 seconds after the last change and any additional change delays the reaction to be postponed to 2 seconds after it. This means that if you write continuously for 10 minutes without 2 a second break, no call is going to be made until you finish typing.

If you have a better idea of how this can be improved, I'm happy to implement it, but I'm not considering doing a call every key stroke :)

**Comment by alan-null** [comment]
@AdamNaj 
I've already implemented the improvement for that. Take a look here: e61651dc17944be61e777eaad33c984d9c28d137 (pull request #795)
