### ISSUE TITLE
Read-Variable errors for empty integer field value

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#802]
`Read-Variable` dialog throws an error when when integer field values are empty. Unfortunately this prevents the validator scriptblock from running.

![image](https://cloud.githubusercontent.com/assets/933163/22135218/6a1d5c36-de92-11e6-91cf-1e6a252b291a.png)

**Comment by michaellwest** [comment]
Now it works.

![image](https://cloud.githubusercontent.com/assets/933163/22135260/b796b804-de92-11e6-9829-5210575ed96a.png)

**Comment by AdamNaj** [comment]
Unfortunately the implementation you proposed (as well as the previous one to large degree) had a chance to change the type of variable from e.g. int to string.

That would cause scripts to fail if the variable was declared e.g. as follows:
```powershell
[int]$number
```
I've submitted my attempt that uses the IConvertible interface of the supported types to do the same and always result in the same type if at all possible, otherwise return the string implementation provided by the user.

**Comment by michaellwest** [comment]
Thanks @AdamNaj for the improvement.

**Comment by AdamNaj** [comment]
You're most welcome :)
