### ISSUE TITLE
Anonymous access

### ISSUE THREAD

**Issue by tmamedbekov** [SitecorePowerShell/Console#822]
I cannot hit the query /-/script/v2/master/ShowLogTail. While I am logged out of SiteCore. I adjust the permissions in the  \App_Config\Include\Cognifide.PowerShell.config. But nothing happens.

I changed:

```
<restfulv2 enabled="true" requireSecureConnection="false">
<authorization>
<add Permission="Allow" IdentityType="User" Identity="extranet\Anonymous" />
<add Permission="Allow" IdentityType="User" Identity="sitecore\Anonymous" />
</authorization>
</restfulv2>
```

**Comment by AdamNaj** [comment]
The configuration appears to be fine.
What I suspect you are missing is the scripts in the "web" database.

Since you are showing up at the service as an anonymous user - the service is not allowing you access to the "master" database and instead in the background replaces the `/master/` with `/web/`.

For the scenario above to work you need to at least publish the SPE templates and scripts involved, meaning
`/Sitecore/templates/Modules/PowerShell Console` - and subitems
and 
`/Sitecore/system/Modules/PowerShell/Script Library/Your Module` and subitems (naturally you need the ancestors to the item as well but be sure not to publish the other items so that you do not open your server up to some vulnerability with this.

The module that lands in the web database needs to be enabled to be picked up by the WebAPI.

I've verified that this scenario then works, even though I would be cautious to do this on a production machine. I would much rather call the URL with the proper "user" and "password" parameters.
