### ISSUE TITLE
Content Editor-Insert Item integration point items should be visible in the ribbon as well

### ISSUE THREAD

**Issue by alan-null** [SitecorePowerShell/Console#860]
As a user I want to be able to use my extra insert options defined in **Content Editor->Insert Item** integration point not only in contextual menu (insert item from context menu) but also from the ribbon.

Righ now **Insert Item** integration point items do not appear in the ribbon. See image below

![image](https://cloud.githubusercontent.com/assets/6848691/24035769/2f11bdd0-0af7-11e7-9d8e-3aa9f16e5955.png)

* `Site folder` is a standard insert option defined in standard values of the item
* `Site` comes from the integration point

**Comment by michaellwest** [comment]
Don't think I ever tried that option. Makes sense to have it though.

**Comment by AlexKasaku** [comment]
I can see how this could be changed to work but I'm not sure of the best way to maintain backwards compatibility with existing script libraries.

Currently the integration works by overriding the default `ItemNew` command, which is what is fired when you use the Content Editor Item context menu. This then executes the `uiGetMasters` pipeline to get all of the "masters" of the item, which represent the items that are listed in a template's Insert Options, before the new command then runs the SPE scripts to add items in addition to this.

If instead, the integration point was inside the `uiGetMasters` pipeline, the items added would be reflected in the ribbon as well.

This would be straightforward to switch to use this pipeline instead of the command, but it would make the integration point name of the integration - "Content Editor / Insert Item" - inaccurate. If this name was however changed to more accurately reflect where the integration happens, this would cause a backwards compatibility problem with existing scripts.

Thoughts? Is there something I'm missing that might mean that `uiGetMasters` is not an appropriate place for the integration?

**Comment by alan-null** [comment]
I remember that I had a discussion with @AdamNaj 1-2 years ago and there was at least one drawback but I can remember now. Hmm was there a different method than `uiGetMasters` before?

**Comment by AdamNaj** [comment]
I think I figured out how to do this! We can get rid of the original integration point and use a completely new method that will not preclude other modules from integating with the Insert command like we do now! This is actually quite an interesting way as it enables AddMasters chaining... commit coming shortly.

**Comment by AlexKasaku** [comment]
Nice one - before you spent too long looking at it, did you see my comment Adam? 😄

**Comment by AdamNaj** [comment]
I did, and I explored this path before but was missing one crucial creative idea that I came up with this time.  I'm renaming the existing command and plugging my command in, and then when it turns out that I shouldn't be handling it, I'm falling back to the previous Sitecore implementation. The code is already committed above.

**Comment by AlexKasaku** [comment]
Ace, I saw the commit! Do you think the integration name should remain the same? It's now slightly inaccurate but changing it could create backwards compatibility issues?

**Comment by AdamNaj** [comment]
It's still `Content Editor` and it's still doing the `Insert Item`, so I think it's named pretty accurately :)

**Comment by AdamNaj** [comment]
Implemented
