### ISSUE TITLE
List View Action Script $selectedData is empty

### ISSUE THREAD

**Issue by SHaberm** [SitecorePowerShell/Console#918]
Running SPE 4.5 on Sitecore 7.2.  We create an array of PSCustomObjects and then pass that to the Show-ListView command.  That works great.  Setup an Action Script for the PSCustomObject and the action shows up in the List View as expected.  The only problem is in the action, no results are returned.  For example, the 
foreach($object in $selectedData)
the $object is always emtpy.

Is this a bug or am I doing something wrong?

**Comment by AlexKasaku** [comment]
Hi @SHaberm, would you be able to upload a package with the script items in that demonstrates the issue?

**Comment by michaellwest** [comment]
Please reopen the issue if you can provide additional details.

**Comment by vaishali4** [comment]
> 
> 
> Running SPE 4.5 on Sitecore 7.2. We create an array of PSCustomObjects and then pass that to the Show-ListView command. That works great. Setup an Action Script for the PSCustomObject and the action shows up in the List View as expected. The only problem is in the action, no results are returned. For example, the
> foreach($object in $selectedData)
> the $object is always emtpy.
> 
> Is this a bug or am I doing something wrong?

HI @SHaberm , Please let me know if the issue is resolved for you as I am also facing the same issue in SPE 4.7 Sitecore 8.2. 
$selectedData is always coming empty for me for PSCustomObject passed to Show-ListView command.

**Comment by michaellwest** [comment]
@vaishali4 The only reason I can think is either no items are selected in the List or there was a bug in that version. I just tested with the latest release and it appears to work as expected.

**Comment by michaellwest** [comment]
I created a new report with the following:

```powershell
1..10 | ForEach-Object {
    [PSCustomObject]@{
        "Genre" = "Comedy"
    }
} | Show-ListView
```

Then an action with the following:

```powershell
foreach($object in $selectedData) {
  Write-Host $object.Genre
}

Show-Result -Text
```

![image](https://user-images.githubusercontent.com/933163/71549192-e0103c80-297e-11ea-81d0-abf34829bca6.png)

**Comment by vaishali4** [comment]
Hi @michaellwest , thanks for looking into this. It seems to be a version issue then as I am able to get alerts from my PSCustomObject action script but alerts under foreach($items in $selectedData) condition don't pop-up/execute.
![image](https://user-images.githubusercontent.com/13902575/71567857-20abab00-2a90-11ea-9927-03b807e28f73.png)

I have now changed the logic to use items instead of object and will see if it fulfills the requirement.
I am trying to develop a search-replace tool that gives a preview of fields which contains old text and on the basis of selection only particular fields of that item gets updated.

Using Item action, I am able to select an item and loop through **all the** fields that contains "old text" and update them but it seems field level selection is not possible through this logic. 

![image](https://user-images.githubusercontent.com/13902575/71568067-3621d480-2a92-11ea-8b8d-0c620f7011ca.png)

Not possible to upgrade currently in higher/PROD env.

**Comment by michaellwest** [comment]
I certainly hope you get it working for your version. Feel free to reach out to the Sitecore.Chat site. There is a channel just for SPE.

You may get some ideas from this tool available in more recent versions. https://github.com/SitecorePowerShell/Console/issues/1027
