### ISSUE TITLE
Index Viewer missing from Authorable Reports package in 4.6

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#920]
Diego reported on slack that the Index Viewer is missing from the Authorable Reports package.

**Comment by AlexKasaku** [comment]
Judging by the further chat on Slack, I think this was just due to the Authorable Reports package having not been installed.

I've ran the script to build the package and Index Viewer is included, and I downloading the 4.6 zip from the Releases page of GitHub and it appears to have the Index Viewer too.
