### ISSUE TITLE
ISE Full Screen missing script path in header

### ISSUE THREAD

**Issue by michaellwest** [SitecorePowerShell/Console#927]
Opening the ISE from the Launchpad results in a window missing the script path. 

The following appears to be a consequence of that:

![2017-08-09_16-05-37](https://user-images.githubusercontent.com/933163/29144037-f671b834-7d1c-11e7-9a12-7ff0426ab2c3.gif)

**Comment by AlexKasaku** [comment]
This looked like it was causing by some code refactoring a good while ago, leading to some code that was meant to be executing on startup being moved into the `change` event of the editor!

Do you think there is still a bug related to the script path?

**Comment by michaellwest** [comment]
I think so. Won't know for sure until we fix it!

**Comment by AlexKasaku** [comment]
Well the bug in the GIF is now fixed, at least, by the previous commit :)

**Comment by AlexKasaku** [comment]
I see what you mean now @michaellwest, I misinterpreted the title. Thought that jumping bug is now fixed, we still want to see this header appear when launching from Launchpad:

![missing_header](https://user-images.githubusercontent.com/1439631/29459010-cf143b0a-8419-11e7-9256-deac5b8fa0ad.png)

**Comment by AdamNaj** [comment]
@michaellwest, @AlexKasaku. This is not fixable because the ISE in full-screen mode does not have a header - only the Launchpad bar that is used to show logged-in users and serves as a placeholder for the Launchpad button. 

The same problem is exhibited by every other app launched in full-screen mode. e.g. Access Viewer looks as follows:

![image](https://github.com/SitecorePowerShell/Console/assets/1209953/86e5c469-e876-46f2-8def-ecb0dd7f8e2a)

In 8.0 this will be less of a problem as we will have Tabs as implemented in #1332. 

![image](https://github.com/SitecorePowerShell/Console/assets/1209953/f209fffa-1974-47a7-85c3-77abb8c53d61)
 
The tab will show the script name all the time, but hovering over it will show the tooltip with the full path.

I'll close this issue as it is not one.
