### ISSUE TITLE
Remoting: Wait-RemoteScriptSession throws exception when remote script is done

### ISSUE THREAD

**Issue by GlennvG** [SitecorePowerShell/Console#966]
When using Wait-RemoteScriptSession it is polling the remote script every 5 seconds. But when the remote script is finished it throws an error that the script session cannot be found.

**Code:**

Wait-RemoteScriptSession -Session $session -Id $jobId -Delay 5 -Verbose

**Logging:**

2017-12-19T12:48:06.5154815Z VERBOSE: Polling job b7668a0c-421a-4703-b94a-e111af7e30c7. Status : Busy.
2017-12-19T12:48:11.5207123Z VERBOSE: Checking the Runspace for the variable id.
**2017-12-19T12:49:20.6055452Z ##[error]The script session with Id 'b7668a0c-421a-4703-b94a-e111af7e30c7' cannot be found.**
2017-12-19T12:49:20.6057975Z VERBOSE: Polling job . Status : .
2017-12-19T12:49:20.6059073Z VERBOSE: Finished polling job b7668a0c-421a-4703-b94a-e111af7e30c7.
2017-12-19T12:49:20.6061579Z VERBOSE: Checking the Runspace for the variable id.
**2017-12-19T12:49:20.9194256Z Get-ScriptSession : The script session with Id 'b7668a0c-421a-4703-b94a-e111af7e30c7' cannot be found.
2017-12-19T12:49:20.9195444Z At line:2 char:36
2017-12-19T12:49:20.9195935Z +         $backgroundScriptSession = Get-ScriptSession -Id $params.__using_id
2017-12-19T12:49:20.9196430Z +                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-12-19T12:49:20.9196997Z     + CategoryInfo          : ResourceUnavailable: (b7668a0c-421a-4703-b94a-e111af7e30c7:String) [Get-ScriptSession],  
2017-12-19T12:49:20.9197511Z    ObjectNotFoundException
2017-12-19T12:49:20.9198138Z     + FullyQualifiedErrorId : ScriptSessionNotFound,Cognifide.PowerShell.Commandlets.ScriptSessions.GetScriptSessionCo 
2017-12-19T12:49:20.9198805Z    mmand**

**Comment by michaellwest** [comment]
Hi @GlennvG, what version of Sitecore, SPE, and the SPE Remoting module are you using?

**Comment by GlennvG** [comment]
Hi @michaellwest 

Sitecore: 8.2.5
SPE: 4.7
Remoting: 4.7

**Comment by michaellwest** [comment]
Would it be possible to provide a sample script for me to test with? Otherwise can you provide details about what your script is doing?

If the application pool recycles then that may lead to the session disappearing.

**Comment by GlennvG** [comment]
This is the script, we are installing 2 tds packages with only items:

`$jobId = Invoke-RemoteScript -Session $session -ScriptBlock { 
		Install-UpdatePackage -Path "$Package1" -UpgradeAction Upgrade -InstallMode Install
                Install-UpdatePackage -Path "$Package2" -UpgradeAction Upgrade -InstallMode Install

		Publish-Item -Id {11111111-1111-1111-1111-111111111111} -Recurse -PublishMode Smart -Database master
	} -AsJob -Verbose`

**Comment by BIGANDYT** [comment]
Hey did anyone find a workaround or fix for this?

**Comment by winklermat** [comment]
Hi @michaellwest

We are using the remoting feature to execute index rebuilds and migration scripts in our CI/CD pipeline.
We regulary encounter the following error - especially when executing long running scripts:

```
The script session with Id '{SOME-GUID-HERE}' cannot be found.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\SPE\Wait-RemoteScriptSession.ps1:73 char:21
```

We set the `Cognifide.PowerShell.PersistentSessionExpirationMinutes` setting to 120 minutes but that didn't solve the problem completely. After some digging in the source code I found out, that the script session is stored in the HttpRuntimeCache.

https://github.com/SitecorePowerShell/Console/blob/bf1e23da55de28deb2ba6c83af38f58fb0783a7c/Cognifide.PowerShell/Commandlets/ScriptSessions/BaseScriptSessionCommand.cs#L39
https://github.com/SitecorePowerShell/Console/blob/0f3353376e3eaae35e6c7d72cf3df8fe63386bae/Cognifide.PowerShell/Core/Host/ScriptSessionManager.cs#L128

Although the cache is configured with `NoAbsoluteExpiration`, there is no guarantee that the cache can not be cleared while running a script in a remote session and therefore losing the remoting connection to the server. A reason can be low memory on the web server. See: https://social.msdn.microsoft.com/Forums/vstudio/en-US/e9c0d73f-f2e7-476d-9a78-d6f65501190a/httpruntime-cache-value-automatically-cleares?forum=wcf

Shouldn't the implementation be changed so that the script sessions are stored in a more persistent and reliable storage instead of using the HttpRuntimeCache?

We are using:

- Sitecore 8.2
- SPE 4.7

**Comment by AlexKasaku** [comment]
We should be able to address this by altering the `CacheItemPriority` to `CacheItemPriority.NotRemovable`, which will prevent items being cleared due to low memory. I think this should probably be configurable so it's a setting you would need to enable.

Whilst we could look at a different storage mechanism, the sessions would need to be serializable which is unlikely to be easily achievable.  

@winklermat - Though any changes would go into the next release of Sitecore. I could provide you with a 4.7 build of a patched assembly with that change in for you to test with, if you like?

**Comment by winklermat** [comment]
@AlexKasaku: Yes, I would like to test the patched version :)

**Comment by AlexKasaku** [comment]
@winklermat  - Please drop the following into your Sitecore instance, backing up the existing assembly first:

https://www.dropbox.com/s/xirxy4k3uj2n31k/Cognifide.PowerShell.dll?dl=0

Let me know if that works. It doesn't require a configuration change, I've just made the change directly.

If you need any further assistance with getting this working, it's best to join the Sitecore Slack and message me on there or join #module-spe. You can register via https://sitecore.chat/

**Comment by AlexKasaku** [comment]
@winklermat - Any luck with this?

**Comment by winklermat** [comment]
@AlexKasaku: Thank you for the patch. I didn't have the time yet to test your change. I will post my feedback here as soon as we tested. I hope to be able to do it in our next sprint.

**Comment by winklermat** [comment]
@AlexKasaku: We applied the patch to our codebase and our nightly deployments are now running without any problems since one week :)
I think your change solved the problem with the failing remoting connection.
Thank you! 👍😁

**Comment by AlexKasaku** [comment]
@winklermat - That's great news! Thanks for letting us know, I'll be merging the fix in which will hopefully be going into the next release. It will be disabled by default to avoid any circumstances of memory not being freed, but can be enabled through configuration for circumstances such as yours.

Thanks again for reporting and helping us to diagnose, you essentially solved the problem :)

**Comment by AlexKasaku** [comment]
Added in new configuration to prevent the cleanup of sessions. To enable this feature, you must override `Spe.PreventPersistentSessionCleanup` in `Spe.config` and set this to `true`,
